# Generated by Django 3.2.2 on 2021-05-09 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stats', models.JSONField()),
                ('evolve_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolve_to', related_query_name='evolve_to_2', to='pokemon.pokemon')),
            ],
        ),
    ]
